ParentAgent/Models/Parent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ParentAgent.Models
{
    public class Parent
    {
        public Parent()
        {
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ParentId { get; set; }

        [Required]
        [MaxLength(100)]
        public string Username { get; set; }

        [Required]
        [MaxLength(100)]
        public string Email { get; set; }

        [Required]
        [MaxLength(50)]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(50)]
        public string LastName { get; set; }

        [Required]
        public int Gender { get; set; }

        [Required]
        [MaxLength(50)]
        public string Phone { get; set; }

        [Required]
        [MaxLength(50)]
        public string Street1 { get; set; }

        [MaxLength(50)]
        public string Street2 { get; set; }

        [Required]
        [MaxLength(50)]
        public string City { get; set; }

        [Required]
        [MaxLength(50)]
        public string State { get; set; }

        [Required]
        [MaxLength(50)]
        public string Zip { get; set; }

        [Required]
        public string NumOfChildren { get; set; }

        [Required]
        public List<Student> Children { get; set; }

        [Required]
        public int Active { get; set; }

        [Required]
        public DateTime DateCreated { get; set; }

        public DateTime? LastConnect { get; set; }

        //public List<QuestionHistory> QuestionHistorys { get; set; }


        //--------------- Not Mapped ---------------
        public string Address
        {
            get
            {
                string result = Street1;

                if (Street2 != null)
                {
                    if (Street2.Length > 0)
                        result += " " + Street2;
                }

                result += " " + City + ", " + State + " " + Zip;

                return result;
            }
        }

        public string PronounPossesion
        {
            get
            {
                if (Gender == 1)
                    return "his";
                else if (Gender == 2)
                    return "her";
                else
                    return "their";
            }
        }

        public string FullNameWithHonorific
        {
            get
            {
                string result = FirstName + " " + LastName;

                if (Gender == 1)
                    return "Mr. " + result;
                else if (Gender == 2)
                    return "Mrs. " + result;
                else
                    return result;
            }
        }

        public string FullNameWithHonorificWithPossesion
        {
            get
            {
                string lastNamePossesive = LastName;
                lastNamePossesive = lastNamePossesive.EndsWith("s") ? lastNamePossesive + "'" : lastNamePossesive + "'s";

                string result = FirstName + " " + lastNamePossesive;

                if (Gender == 1)
                    return "Mr. " + result;
                else if (Gender == 2)
                    return "Mrs. " + result;
                else
                    return result;
            }
        }

        public string Honorific
        {
            get
            {
                if (Gender == 1)
                    return "Mr.";
                else if (Gender == 2)
                    return "Mrs.";
                else
                    return "";
            }
        }
        //--------------- end of Not Mapped ---------------
    }


    public enum Gender
    {
        Male = 1,
        Female = 2,
        Other = 3
    }

    public enum ClassType
    {
        Regular = 1,
        PreAP = 2,
        AP = 3
    }

    public enum PreferredMethodOfContact
    {
        Email = 1,
        Text = 2,
        Phone = 3
    }
}

ParentAgent/Models/ParentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ParentAgent.Models
{
    public class ParentViewModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ParentId { get; set; }

        [Required]
        [MaxLength(100)]
        public string Username { get; set; }

        [Required]
        [MaxLength(100)]
        public string Email { get; set; }

        [Required]
        [MaxLength(50)]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(50)]
        public string LastName { get; set; }

        [Required]
        public int Gender { get; set; }

        [Required]
        [MaxLength(50)]
        public string Phone { get; set; }

        [Required]
        [MaxLength(50)]
        public string Street1 { get; set; }

        [MaxLength(50)]
        public string Street2 { get; set; }

        [Required]
        [MaxLength(50)]
        public string City { get; set; }

        [Required]
        [MaxLength(50)]
        public string State { get; set; }

        [Required]
        [MaxLength(50)]
        public string Zip { get; set; }

        [Required]
        public string NumOfChildren { get; set; }

    }
}

ParentAgent/Controllers/StaffController.cs
using ParentAgent.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net.Mail;
using ParentAgent.Helpers;

namespace ParentAgent.Controllers
{
    [Authorize(Roles = "omniscient, staff")]
    public class StaffController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //private List<Parent> theseParents;

        //public List<Parent> oParents {
        //    get {
        //        if (theseParents == null)
        //            theseParents = (List<Parent>)Session["oParents"];

        //        return theseParents;
        //    }
        //    set {
        //        theseParents = value;
        //        Session["oParents"] = theseParents;
        //    }
        //}


        [Route("{queryvalues:string}")]
        public ActionResult Index(string queryvalues = "")
        {
            ViewBag.Title = "Dashboard - Staff";

            string reportName = queryvalues;

            //-- Parent --
            List<Parent> oParents = new List<Parent>();
            List<QuestionHistory> oQuestionHistorys = new List<QuestionHistory>();

            if (reportName == "ViewParents_withNewQuestions")
                oParents = db.QuestionHistorys.Include(q => q.Parent).Where(q => q.Answer.Length == 0 || q.Answer == null).Select(q => q.Parent).Distinct().ToList();//oParents = db.Parents.Include(p => p.Children.Select(s => s.Courses.Select(c => c.QuestionHistorys.Count > 0))).ToList();

            else if (reportName == "ViewParents_Active") //ToDo: wwwsss Start using DataTables and combine reports where possible.
                oParents = db.Parents.Where(p => p.Active == 1).ToList();

            else if (reportName == "ViewParents_Inactive")
                oParents = db.Parents.Where(p => p.Active != 1).ToList();

            else if (reportName == "ViewParents_All")
                oParents = db.Parents.ToList();

            else if (reportName == "ViewParents_New")
            {
                DateTime rangeDate = DateTime.Now.AddDays(-7);
                oParents = db.Parents.Where(p => p.DateCreated > rangeDate).ToList();
            }
            else if (reportName == "ViewParents_neverAskedQuestions")
            {
                //oParents = db.Parents.Include(p => p.Children.Select(s => s.Courses.Select(c => c.QuestionHistorys))).ToList();
                oParents = db.Parents.Where(p => p.Children.Any(s => s.Courses.Any(c => c.QuestionHistorys.Any(q => q.Parent.ParentId != p.ParentId)))).ToList();//oParents = db.Parents.Include(p => p.Children.Select(s => s.Courses.Select(c => c.QuestionHistorys.Select(q => q.Answer.Length == 0)))).ToList();
            }
            else if (reportName == "ViewQuestions_Pending")
                oQuestionHistorys = db.QuestionHistorys.Include(q => q.Parent).Include(q => q.Student).Include(q => q.Course).Where(q => q.Answer.Length == 0 || q.Answer == null).OrderBy(q => q.Parent.LastName).ThenBy(q => q.Parent.FirstName).ThenBy(q => q.Student.FirstName).ThenBy(q => q.Course.Name).ThenByDescending(q => q.QuestionHistoryId).ToList();

            else if (reportName == "ViewQuestions_All")
                oQuestionHistorys = db.QuestionHistorys.Include(q => q.Parent).Include(q => q.Student).Include(q => q.Course).OrderBy(q => q.Parent.LastName).ThenBy(q => q.Parent.FirstName).ThenBy(q => q.Student.FirstName).ThenBy(q => q.Course.Name).ThenByDescending(q => q.QuestionHistoryId).ToList();


            ResponseReportsViewModel oRVM = new ResponseReportsViewModel()
            {
                NameOfReport = reportName,
                Parents = oParents,
                QuestionHistorys = oQuestionHistorys
            };

            return View(oRVM);
        }


        [Route("{queryvalues:int}")]
        public ActionResult Parent(int queryvalues)
        {
            ViewBag.Title = "Dashboard - Staff";

            int id = queryvalues;

            Parent oParent = db.Parents.SingleOrDefault(p => p.ParentId == id);
            List<QuestionHistory> oQuestionHistorysResponded = db.QuestionHistorys.Include(qh => qh.Student).Include(qh => qh.Course).Where(qh => qh.Parent.ParentId == id && !(qh.Answer == null || qh.Answer.Length == 0)).OrderBy(q => q.Parent.LastName).ThenBy(q => q.Parent.FirstName).ThenBy(q => q.Student.FirstName).ThenBy(q => q.Course.Name).ThenByDescending(q => q.QuestionHistoryId).ToList();
            List<QuestionHistory> oQuestionHistorysPending = db.QuestionHistorys.Include(qh => qh.Student).Include(qh => qh.Course).Where(qh => qh.Parent.ParentId == id && (qh.Answer == null || qh.Answer.Length == 0)).OrderBy(q => q.Parent.LastName).ThenBy(q => q.Parent.FirstName).ThenBy(q => q.Student.FirstName).ThenBy(q => q.Course.Name).ThenByDescending(q => q.QuestionHistoryId).ToList();

            ResponseQuestionsViewModel oRVM = new ResponseQuestionsViewModel()
            {
                Parent = oParent,
                QuestionHistoryVM = new QuestionHistoryViewModel(),
                QuestionHistorys = oQuestionHistorysResponded,
                QuestionHistorysPending = oQuestionHistorysPending
            };

            return View(oRVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SendEmailsToTeachers(ResponseQuestionsViewModel oRVM)
        {
            TempData["UserMessage"] = new MessageVM() { IsSuccessful = false, Title = "Error!", Message = "Something went wrong." };

            if (!ModelState.IsValid)
                return View(oRVM);

            //-- Parent --
            Parent oParent = db.Parents
                .Include(p => p.Children.Select(s => s.Courses.Select(c => c.Teacher)))
                .Include(p => p.Children.Select(s => s.Courses.Select(c => c.QuestionHistorys)))
                .SingleOrDefault(p => p.ParentId == oRVM.QuestionHistoryVM.ParentId);

            //Parent oParent = db.Parents.Include(p => p.Children.Select(s => s.Courses.Select(c => c.Teacher))).SingleOrDefault(p => p.ParentId == oRVM.QuestionHistoryVM.ParentId);
            //Parent oParent = db.Parents.Include(p => p.Children.Select(s => s.Courses)).Select(p => new { Parent = p, Children = p.Children, Teacher = p.Children.Select(s => s.Courses.Select(c => c.Teacher)), QuestionHistorys = p.Children.Select(s => s.Courses.Select(c => c.QuestionHistorys)) }).SingleOrDefault(p => p.ParentId == oRVM.QuestionHistoryVM.ParentId);
            //Parent oParent = db.Parents.Include(p => p.Children.Select(s => s.Courses)).SingleOrDefault(p => p.ParentId == oRVM.Parent.ParentId);

            if (oParent == null) //Error. Parent DNE.
                throw new ArgumentException("SendEmailsToTeachers(ResponseQuestionsViewModel oRVM) - Parent DNE.");
            //-- end of Parent --

            try
            {
                string questions;
                int questionNumber;
                foreach (Student iStudent in oParent.Children)
                {
                    foreach (Course iCourse in iStudent.Courses)
                    {
                        if(iCourse.QuestionHistorys.Count > 0)
                        {
                            questions = "";
                            questionNumber = 1;

                            foreach (QuestionHistory iQuestionHistory in iCourse.QuestionHistorys)
                            {
                                questions += questionNumber++ + ". " + iQuestionHistory.QuestionTxt + "<br /><i>your answer here</i><br /><br />";
                            }

                            if(!SendEmail(oParent, iStudent, iCourse, questions))
                                return RedirectToAction("Parent", new { queryvalues = oParent.ParentId });
                        }
                    }
                }
            }
            catch (Exception e)
            {
                return RedirectToAction("Parent", new { queryvalues = oParent.ParentId });
            }

            TempData["UserMessage"] = new MessageVM() { IsSuccessful = true, Title = "Success!", Message = "Your question(s) for this parent have been successfully sent." };

            return RedirectToAction("Parent", new { queryvalues = oParent.ParentId });
        }


        public bool SendEmail(Parent oParent, Student oStudent, Course oCourse, string Questions)
        {
            Teacher oTeacher = oCourse.Teacher;
            List<QuestionHistory> oQuestionHistorys = oCourse.QuestionHistorys;
            string body = "<p>Hi,</p>" +
                "<p>" + oParent.FullNameWithHonorific + " has asked us to contact you regarding " + oParent.PronounPossesion + " child " + oStudent.FirstName + " " + oStudent.LastName + ". Please reply to this email with answers to the question(s) below.</p>" +
                "<p>You can simply scroll down and place your answers below each question. If you prefer to talk over the phone, please reply to this email requesting a call.</p>" +
                "<p><h1>Questions</h1>" + Questions + "</p>";

            string footer = "<p><b>About Us</b>: Our group of professionals help parents and teachers communicate more effectively in order to improve children's performance in school.  We have a track record of helping students increase their grades and participation in school.  We absolutely love our communities and cannot wait to work with you!  You can find out more about us <a href='https://ParentAgent.com'>here</a>.</p>";

            body += footer;


            MailMessage mailMessage = new MailMessage();
            mailMessage.From = new MailAddress("admin@parentagent.com");
            mailMessage.To.Add(new MailAddress(oTeacher.Email));
            mailMessage.IsBodyHtml = true;
            mailMessage.Subject = oStudent.FirstName + " " + oStudent.LastName + " - " + oCourse.Name + " - Parent Agent";

ParentAgent/Views/Staff/Parent.cshtml
@model ParentAgent.Models.ResponseQuestionsViewModel
@{
    var oParent = Model.Parent;
    var oQuestionHistorysResponded = Model.QuestionHistorys;
    var oQuestionHistorysPending = Model.QuestionHistorysPending;
}

<!-- full Title -->
<div class="full-title">
    <div class="container">
        <!-- Page Heading/Breadcrumbs -->
        <h1 class="mt-4 mb-3"> Contact </h1>
        <div class="breadcrumb-main">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/Index">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="/Dashboard/Index">Dashboard (Staff)</a>
                </li>
                <li class="breadcrumb-item active">Questions</li>
            </ol>
        </div>
    </div>
</div>

<div class="contact-main">
    <div class="container">
        <div class="row">


            <!-- -------------------- RESULTS -------------------- -->
            <div class="col-md-12">

                <!-- ---------- Parent Info ---------- -->
                <div class="card">
                    <div class="card-header">@oParent.FirstName @oParent.LastName</div>
                    <div class="card-body">
                        <table class="table table-striped table-responsive table-hover">
                            <tr class="">
                                <td class="">Username</td>
                                <td class="">@oParent.Username</td>
                            </tr>
                            <tr class="">
                                <td class="">Active</td>
                                <td class="">@oParent.Active</td>
                            </tr>
                            <tr class="">
                                <td class="">Gender</td>
                                <td class="">@oParent.Gender</td>
                            </tr>
                            <tr class="">
                                <td class="">NumOfChildren</td>
                                <td class="">@oParent.NumOfChildren</td>
                            </tr>
                            <tr class="">
                                <td class="">Email</td>
                                <td class="">@oParent.Email</td>
                            </tr>
                            <tr class="">
                                <td class="">Phone</td>
                                <td class="">@oParent.Phone</td>
                            </tr>
                            <tr class="">
                                <td class="">Address</td>
                                <td class="">@oParent.Address</td>
                            </tr>
                            <tr class="">
                                <td class="">Date Joined</td>
                                <td class="">@oParent.DateCreated</td>
                            </tr>
                            <tr class="">
                                <td class="">Last Logged In</td>
                                <td class="">@oParent.LastConnect</td>
                            </tr>
                        </table>
                    </div>
                </div>
                <br />
                <!-- ---------- end of Parent Info ---------- -->
                <!-- ---------- Questions ---------- -->
                @{
                    if (oQuestionHistorysPending.Count > 0)
                    {
                        <div class="card">
                            <div class="card-header">
                                Questions (Pending)
                                <!-- Send Emails -->
                                <div class="float-right">
                                    @using (Html.BeginForm("SendEmailsToTeachers", "Staff", FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()

                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                        <input type="hidden" id="QuestionHistoryVM_ParentId" name="QuestionHistoryVM.ParentId" value="@oParent.ParentId" />
                                        <input type="hidden" id="QuestionHistoryVM_QuestionTxt" name="QuestionHistoryVM.QuestionTxt" value="trash" />
                                        <input type="submit" value="Send ALL Emails to ALL Teachers" class="btn btn-primary js-btn-hover" />
                                    }
                                </div>
                                <!-- end of Send Emails -->
                            </div>
                            <div class="card-body">
                                <table class="table table-sm table-striped table-hover">
                                    @*<colgroup>
                                            <col class="col-md-1">
                                            <col class="col-md-1">
                                            <col class="col-md-4">
                                            <col class="col-md-2">
                                            <col class="col-md-2">
                                            <col class="col-md-2">
                                        </colgroup>*@
                                    <thead>
                                        <tr class="d-flex">
                                            <th class="col-md-1">Student</th>
                                            <th class="col-md-1">Course</th>
                                            <th class="col-md-4">Parent Question</th>
                                            <th class="col-md-1">Num Of Times Sent To Teacher</th>
                                            <th class="col-md-2">Teacher Response</th>
                                            <th class="col-md-2">Parent Agent Notes</th>
                                            <th class="col-md-1">Last Updated</th>
                                        </tr>
                                    </thead>
                                    @{
                                        foreach (var iQuestionHistory in oQuestionHistorysPending)
                                        {
                                            Model.QuestionHistoryVM.QuestionTxt = iQuestionHistory.QuestionTxt;

                                            <tr class="d-flex">
                                                <td class="col-md-1">@iQuestionHistory.Student.FullName</td>

                                                <td class="col-md-1">@iQuestionHistory.Course.Name</td>

                                                <td class="col-md-4">
                                                    @*@Html.DisplayFor(model => iQuestionHistory.QuestionTxt)*@
                                                    @using (Html.BeginForm("EditQuestionHistory", "Parent", FormMethod.Post))
                                                    {
                                                        @Html.AntiForgeryToken()


                                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                                        <div class="form-group">
                                                            <div class="col-md-12">
                                                                @Html.EditorFor(model => model.QuestionHistoryVM.QuestionTxt, new { htmlAttributes = new { @class = "form-control", @cols = 10, @rows = 4 } })
                                                                @Html.ValidationMessageFor(model => model.QuestionHistoryVM.QuestionTxt, "", new { @class = "text-danger" })
                                                            </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <div class="col-md-offset-2 col-md-10">
                                                                <input type="hidden" id="QuestionHistoryVM_QuestionHistoryId" name="QuestionHistoryVM.QuestionHistoryId" value="@iQuestionHistory.QuestionHistoryId" />
                                                                <input type="hidden" id="QuestionHistoryVM_ParentId" name="QuestionHistoryVM.ParentId" value="@oParent.ParentId" />
                                                                <input type="hidden" id="QuestionHistoryVM_StudentId" name="QuestionHistoryVM.StudentId" value="@iQuestionHistory.Student.StudentId" />
                                                                <input type="hidden" id="QuestionHistoryVM_CourseId" name="QuestionHistoryVM.CourseId" value="@iQuestionHistory.Course.CourseId" />
                                                                <input type="submit" value="Update" class="btn btn-primary js-btn-hover" />
                                                            </div>
                                                        </div>
                                                    }
                                                </td>

                                                <td class="col-md-1">@iQuestionHistory.NumOfTimesSentToTeacher</td>

                                                <td class="col-md-2">@iQuestionHistory.Answer</td>

                                                <td class="col-md-2">@iQuestionHistory.OtherAnswer</td>

                                                <td class="col-md-1">@iQuestionHistory.DateAnswered</td>
                                            </tr>
                                        }
                                    }
                                </table>
                            </div>
                        </div>
                        <br />
                    }

                    if (oQuestionHistorysResponded.Count > 0)
                    {
                        <div class="card">
                            <div class="card-header">
                                Questions (Responded)
                            </div>
                            <div class="card-body">
                                <table class="table table-striped table-responsive table-hover">
                                    <thead>
                                        <tr class="">
                                            <th class="">Parent Question</th>
                                            <th class="">Teacher Response</th>
                                            <th class="">Parent Agent Notes</th>
                                            <th class="">Last Updated</th>
                                        </tr>
                                    </thead>
                                    @{
                                        foreach (var iQuestionHistory in oQuestionHistorysResponded)
                                        {
                                            <tr class="">
                                                <td class="">
                                                    @Html.DisplayFor(model => iQuestionHistory.QuestionTxt)
                                                </td>

                                                <td class="">
                                                    @Html.DisplayFor(model => iQuestionHistory.Answer)
                                                </td>

                                                <td class="">
                                                    @Html.DisplayFor(model => iQuestionHistory.OtherAnswer)
                                                </td>

                                                <td class="">
                                                    @Html.DisplayFor(model => iQuestionHistory.DateAnswered)
                                                </td>
                                            </tr>
                                        }
                                    }
                                </table>
                            </div>
                        </div>
                        <br />
                    }

                }
                <!-- ---------- end of Questions ---------- -->

            </div>
            <!-- -------------------- end of RESULTS -------------------- -->


        </div>
    </div>
    <!-- /.container -->
</div>


@section Scripts {
    <script type="text/javascript">
        //---------- $(document).ready() ----------
$(document).ready(function () {

    //------------------------------ OnLoad ------------------------------

    //----- Success/Failure Message -----
    @if(TempData["UserMessage"] != null)
    {
        var message = (ParentAgent.Helpers.MessageVM)TempData["UserMessage"];

        if (message.IsSuccessful == true)
        {
            @:toastr.success("@message.Title  @message.Message");
        }
        else
        {
            @:toastr.error("@message.Title  @message.Message");
        }
      }
    //----- end of Success/Failure Message -----


    //------------------------------ end of OnLoad ------------------------------
    });
    //---------- end of $(document).ready() ----------
    </script>

}